version: '3.8'

services:
  fastapi:
    build: .  # Build from the Dockerfile in the current directory
    container_name: fastapi_app
    ports:
      - "8000:8000"  # Expose container port 8000 to your local machine
    env_file:
      - .env  # Load environment variables from the .env file
    volumes:
      - .:/app  # (Optional) Mount the current directory for live code updates during development
    command: pipenv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload  # Start command